# Generated by Django 4.1.2 on 2022-11-06 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('num_salas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_nto', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_sala', models.IntegerField()),
                ('num_asientos', models.IntegerField()),
                ('categoria', models.CharField(max_length=50)),
                ('id_cine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.cine')),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('fecha_estreno', models.DateField()),
                ('longitud_mins', models.FloatField()),
                ('id_director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.director')),
                ('id_sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.sala')),
            ],
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_nto', models.DateField()),
                ('peliculas', models.ManyToManyField(to='myapp.pelicula')),
            ],
        ),
    ]
