# Generated by Django 4.1.3 on 2022-11-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_sala_num_sala_sala_cod_sala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='longitud_mins',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sala',
            name='cod_sala',
            field=models.CharField(max_length=50),
        ),
    ]
