# Generated by Django 4.1.3 on 2022-11-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_pelicula_longitud_mins_alter_sala_cod_sala'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='peliculas',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='actores',
            field=models.ManyToManyField(to='myapp.actor'),
        ),
    ]
