# Generated by Django 4.1.3 on 2022-11-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_actor_peliculas_pelicula_actores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='id_sala',
        ),
        migrations.AddField(
            model_name='sala',
            name='peliculas',
            field=models.ManyToManyField(to='myapp.pelicula'),
        ),
    ]
