# Generated by Django 4.1.3 on 2022-11-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_pelicula_id_sala_sala_peliculas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sala',
            name='peliculas',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='salas',
            field=models.ManyToManyField(to='myapp.sala'),
        ),
    ]
