# Generated by Django 4.1.3 on 2022-12-07 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_sala_peliculas_pelicula_salas'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='longitud_horas',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='actores',
            field=models.ManyToManyField(related_name='peliculas', to='myapp.actor'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='id_director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_director', to='myapp.director'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='salas',
            field=models.ManyToManyField(related_name='peliculas', to='myapp.sala'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='id_cine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salas', to='myapp.cine'),
        ),
    ]
