# Generated by Django 4.1.3 on 2022-12-09 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_pelicula_longitud_horas_alter_pelicula_actores_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'verbose_name_plural': 'Actores'},
        ),
        migrations.AlterModelOptions(
            name='director',
            options={'verbose_name_plural': 'Directores'},
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='longitud_horas',
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='id_director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peliculas', to='myapp.director'),
        ),
    ]
